# Generated by Django 5.2.7 on 2025-11-01 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlebook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='googlebook',
            name='categories',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlebook',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlebook',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
